version: '3.8'
services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - data-db:/data/db
    ports:
      - 27017:27017
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - data-mq:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=12345
volumes:
  data-db:
  data-mq: