version: '3.8'
services:
  pauta:
    build:
      context: .
      network: host
    restart: always
    container_name: pauta-api
    ports:
      - 8080:8080
    networks: 
      service-network:
    depends_on:
      - mongodb
      - rabbitmq
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - data-db:/data/db
    networks: 
      service-network:
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - data-mq:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=12345
    networks: 
      service-network:
volumes:
  data-db:
  data-mq:
networks:
  service-network: